default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: covid_data_development
production:
  <<: *default
  database: covid_data_production
  username: covid_data
  password: <%= ENV['COVID_DATA_DATABASE_PASSWORD'] %>
